on:
  push:
    branches:
      # - main
      - autoup

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build pkg
    steps:
      - uses: actions/checkout@v3
      - name: build pkg
        id: build
        uses: ./.github/actions/build
        with:
          version: "0.${{ github.run_number }}.${{ github.run_attempt }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          prerelease: true
          title: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          files: |
            out/nt-atom-v0.${{ github.run_number }}.${{ github.run_attempt }}.zip
            out/checksum.md5
            LICENSE
