on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build pkg
    steps:
      - uses: actions/checkout@v3
      - name: build pkg
        id: build
        uses: ./.github/actions/build
        with:
          version: '${{ github.run_number }}.${{ github.run_attempt }}'
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.run_number }}.${{ github.run_attempt }}"
          prerelease: true
          title: "${{ github.run_number }}.${{ github.run_attempt }}"
          files: |
            out/nt-atom-v${{ github.run_number }}.${{ github.run_attempt }}.zip
            out/checksum.md5
            LICENSE
