on:
  # run automatically in sunday
  schedule:
    - cron: "0 * * * 0"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - dev

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build pkg
    steps:
      - uses: actions/checkout@v3
      - name: build pkg
        id: build
        uses: ./.github/actions/build
        with:
          version: "0.${{ github.run_number }}.${{ github.run_attempt }}"
          target: "update"
      - name: Commit files
        run: |
          ls -la
          date | sudo -u nobody tee auto_update_time.txt
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo git commit -a -m "Bot: Auto Update Packages."
          sudo git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          sudo git push github ${GITHUB_BASE_REF}:autoup
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: autoup
      #     force: true
