on:
  # run automatically in sunday
  schedule:
    - cron: "0 * * * 0"

  # allows to manually run the job at any time
  workflow_dispatch:

  # run on every push on the master branch
  push:
    branches:
      - main
      - dev

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: update and build pkg
    steps:
      - uses: actions/checkout@v3
      - name: update pkg
        id: update
        uses: ./.github/actions/build
        with:
          version: "0.${{ github.run_number }}.${{ github.run_attempt }}"
          target: "update"
      - name: build pkg
        id: build
        uses: ./.github/actions/build
        with:
          version: "0.${{ github.run_number }}.${{ github.run_attempt }}"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          prerelease: true
          title: "v0.${{ github.run_number }}.${{ github.run_attempt }}"
          files: |
            out/nt-atom-v0.${{ github.run_number }}.${{ github.run_attempt }}.zip
            out/checksum.md5
            LICENSE
      - name: Commit files
        run: |
          ls -la
          date | sudo -u nobody tee auto_update_time.txt
          sudo git config --local user.email "github-actions[bot]@users.noreply.github.com"
          sudo git config --local user.name "github-actions[bot]"
          sudo git commit -a -m "Bot: Auto Update Packages."
          sudo git remote add github https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          sudo git push --force github $(git branch --show-current):autoup
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: autoup
      #     force: true
